employees/urls.py
from django.urls import path
from . import views

urlpatterns=[

    path('login',views.user_login),
    path('home',views.user_home),
    
    
    ]

jb_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
   
    path('jseekers/',include('job_seekers.urls')),
    path('jbadmin/',include('job_admin.urls')),
    
]

job_admin/urls.py
from django.urls import path
from . import views

urlpatterns=[
   path('login',views.user_login,name='user'),
    path('view',views.view_emp,name='view_employees'),
   

]

job_seekers/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views
app_name='jbskr'

urlpatterns=[

    path('login',views.user_login),
    path('jobsearch',views.search_job),
    path('jobdetails',views.details_job,name='jobdetails'),
    
    ]

employees/models.py
from django.db import models

# Create your models here.

job_admin/models.py
from django.db import models

# Create your models here.

job_seekers/models.py
from django.db import models

# Create your models here.

employees/views.py
from django.shortcuts import render

# Create your views here.

def user_login(request):
    return render(request,'employees/login.html')

def user_home(request):
    return render(request,'employees/home.html')

job_admin/views.py
from django.shortcuts import render

# Create your views here.

def user_login(request):
    return render(request,'emp/login.html')
def view_emp(request):
    return render(request,'emp/view employees.html')

job_seekers/views.py
from django.shortcuts import render

# Create your views here.

def user_login(request):
    return render(request,'job_seekers/login.html')

def search_job(request):
    return render(request,'job_seekers/jobsearch.html') 
def details_job(request):
    return render(request,'job_seekers/jobdetails.html')     

employees/templates/emp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>home</h1>
</body>
</html>

employees/templates/emp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>login</h1>
</body>
</html>

job_admin/templates/jadmin/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>login</h1>
</body>
</html>

job_admin/templates/jadmin/view employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>view</h1>
</body>
</html>

job_seekers/templates/job_seekers/jobdetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hallooooo
</body>
</html>

job_seekers/templates/job_seekers/jobsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    jobsearch
</body>
</html>

job_seekers/templates/job_seekers/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'jbskr:jobdetails' %}">job details</a>
    <img src="{% static 'images/human.jpg' %}" alt="">
</body>
</html>